[theme]
primaryColor = "#18181b"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f4f4f5"
textColor = "#09090b"
font = "sans serif"

[server]
maxUploadSize = 50
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
